version: "3.7"

volumes:
  data:

services:
  # Prod version of our app
  scovid:
    build: .
    container_name: 'scovid'
    restart: always
    ports:
      - 4001-4002:5000
    volumes:
      - data:/home/app/scovid19/data
    environment:
      FLASK_APP: app
      FLASK_ENV: production
      DATABASE: '/home/app/scovid19/data/scovid19.db'
      SCOVID_ENV: prod
      SCOVID_PROJECT_ROOT: /home/app/scovid19/
    env_file:
      - .env
