version: "3.7"

services:
  scovid:
    build: .
    container_name: 'scovid'
    restart: always
    ports:
      - 4001:5000
    volumes:
      - './scovid19:/home/code/scovid19/scovid19'
      - data:/home/code/scovid19/data
    environment:
      SCOVID_ENV: dev
      SCOVID_PROJECT_ROOT: /home/code/scovid19/
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_APP: scovid19
