name: Auto Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      # Back end formatting with tan
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: 'Run py formatter'
        run: |
          source venv/bin/activate
          black app/

      # Front end formatting with prettier
      - name: Install
        run: yarn add prettier
 
      - name: Run prettier
        run: yarn run prettier --write **.html.j2 **.js **.css

      - name: Cleanup
        run: rm -rf node_modules package.json yarn.lock

      # Commit changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ':art: Auto-format with tan & prettier'
