name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      main

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Run pytest'
        run: |
          # Enable BuildKit
          export DOCKER_BUILDKIT=1
          export COMPOSE_DOCKER_CLI_BUILD=1
          export BUILDKIT_PROGRESS=plain

          # Create an empty .env
          touch .env

          # Build and test
          docker-compose -f docker-compose.yml up --build -d scovid
          docker exec scovid ./tools/update_db.py
          docker exec scovid pytest

  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Run bandit'
        run: |
          # Enable BuildKit
          export DOCKER_BUILDKIT=1
          export COMPOSE_DOCKER_CLI_BUILD=1
          export BUILDKIT_PROGRESS=plain

          # Create an empty .env
          touch .env

          # Build and test
          docker-compose -f docker-compose.yml up --build -d scovid
          docker exec scovid ./tools/update_db.py
          docker exec scovid bandit -c .banditrc -r app/
