name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      main

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Run pytest'
        run: |
          docker-compose up --build -d scovid
          docker exec scovid pytest

  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Run pytest'
        run: |
          docker-compose up --build -d scovid
          docker exec scovid bandit -c .banditrc -r app/
